Hw9
Listoc/tinkoff-java-course-2semestr pull request #10
Opened 2024-04-14 18:16 UTC by Listoc

2024-04-14 18:23 UTC, Listoc commented
Задача 3
### http_server_requests_seconds_count:
![image](https://github.com/Listoc/tinkoff-java-course-2semestr/assets/81486048/2ec62b10-5bf1-4b2b-af82-3a9816cf8d4d)
### http_server_requests_seconds_sum:
![image](https://github.com/Listoc/tinkoff-java-course-2semestr/assets/81486048/d0300c42-3d95-4a47-9cc6-753607ade3ae)
### jvm_gc_memory_allocated_bytes_total
![image](https://github.com/Listoc/tinkoff-java-course-2semestr/assets/81486048/631fd941-5472-4298-9a8f-ab6ccab17a51)
### jvm_memory_used_bytes
![image](https://github.com/Listoc/tinkoff-java-course-2semestr/assets/81486048/14808269-7af5-44a4-902e-f8b35e718be7)

2024-04-14 18:29 UTC, Listoc commented
Задача 4:
Добавил переменную $application, затем в каждой метрике добавил фильтр application = $application
## Bot
![image](https://github.com/Listoc/tinkoff-java-course-2semestr/assets/81486048/3b8c9f27-0e5c-4050-9e6f-3d70ef59b878)

## Scrapper
![image](https://github.com/Listoc/tinkoff-java-course-2semestr/assets/81486048/828026f9-5443-4b62-bcd8-db04d0fd3006)

2024-04-14 18:38 UTC, Listoc commented
Задача 5:
Без фильтра т.к. метрика только с бота идет
![image](https://github.com/Listoc/tinkoff-java-course-2semestr/assets/81486048/7eacf984-75b5-4225-9ab2-4e23fe9c3655)

2024-04-20 16:22 UTC, YuriiKondratov commented
В целом всё ок, но метрики типа counter лучше визуализировать с использованием rate или increase, иначе они будут иметь вид постоянно возрастающих графиков и практически не будут нести полезной информации. Прикрепи пожалуйста скрин с визуализацией messages_counter_total с использованием rate или increase

2024-04-20 16:22 UTC, YuriiKondratov requested changes
Указал выше

2024-04-20 17:00 UTC, Listoc commented
Добавил в комментарий с задачей 5

2024-04-23 06:47 UTC, YuriiKondratov approved these changes

2024-04-23 08:03 UTC, merged