Hw5
Listoc/tinkoff-java-course-2semestr pull request #5
Opened 2024-03-17 19:37 UTC by Listoc

2024-03-24 09:21 UTC, YuriiKondratov requested changes

2024-03-24 09:21 UTC, YuriiKondratov commented on scrapper/src/main/java/edu/java/scrapper/repository/jdbc/JdbcLinkRepository.java
> +    public static RowMapper<Link> getLinkRowMapper() {
У тебя получается, что при каждом запросе будет создаваться один и тот же новый RowMapper. Давай сделаем так, чтобы он создавался только один раз и переиспользовался в запросах.

2024-03-24 09:21 UTC, YuriiKondratov commented on scrapper/src/main/java/edu/java/scrapper/repository/jdbc/JdbcTgChatRepository.java
> +    public static RowMapper<TgChat> getTgChatRowMapper() {
Аналогичное замечаение про RowMapper

2024-03-24 09:21 UTC, YuriiKondratov commented on scrapper/src/main/java/edu/java/scrapper/service/jdbc/JdbcLinkService.java
> +        var link = jdbcLinkRepository.findLinkByUrl(stringUrl);
Я бы посоветовал вместо null перейти на Optional

2024-03-24 09:21 UTC, YuriiKondratov commented on scrapper/src/main/java/edu/java/scrapper/controller/LinksController.java
> +        linkService.remove(id, linkRequest.url());
Обычно в REST апи DELETE метод возвращает пустое тело и 204 код ответа. Это позволяет достичь [идемпотентности](https://developer.mozilla.org/ru/docs/Glossary/Idempotent). Давай тут применим этот принцип - не будем выбрасывать ошибку, если не нашли ссылки для удаления.

2024-03-24 09:21 UTC, YuriiKondratov commented on scrapper/src/main/java/edu/java/scrapper/controller/TelegramChatIdController.java
> +        jdbcTgChatService.unregister(id);
Аналогично removeLink - давай не будем эксепшн бросать если ссылку не нашли. Задача DELETE метода же в том, чтобы ссылки не было в базе. А если её там и так нет - значит всё ок.

2024-03-24 09:21 UTC, YuriiKondratov commented on scrapper/src/main/java/edu/java/scrapper/service/jdbc/JdbcLinkUpdater.java
> +public class JdbcLinkUpdater implements LinkUpdater {
Давай теперь по поводу этого класса.

1) Логика, связанная с обновлением ссылок не зависит от того, как мы получаем доступ к базе (через JDBC, JPA или jOOQ), поэтому здесь взаимодействие с базой должно быть через интерфейсы сервисов, а не через конкретные DAO (jdbcLinkRepository и jdbcTgChatRepository).

2) У тебя жестко захардкожены два источника - github и stackoverflow. Че будем делать когда ещё один источник появится? А когда их станет 100? Давай объединим логику обработки обновлений интерфейсом. Например: `interface LinkUpdateProcessorService { public String process(Link link); }` и сделаем конкретные реализации. Например: `GithubLinkUpdateProcessorService` и `StackOverflowLinkUpdateProcessorService`. Каждый класс будет ходить в свой клиент и проверять наличие обновлений.

2024-03-24 14:46 UTC, Listoc commented on scrapper/src/main/java/edu/java/scrapper/repository/jdbc/JdbcLinkRepository.java
> +    public static RowMapper<Link> getLinkRowMapper() {
Исправил

2024-03-24 14:47 UTC, Listoc commented on scrapper/src/main/java/edu/java/scrapper/repository/jdbc/JdbcTgChatRepository.java
> +    public static RowMapper<TgChat> getTgChatRowMapper() {
Исправил

2024-03-24 14:47 UTC, Listoc commented on scrapper/src/main/java/edu/java/scrapper/service/jdbc/JdbcLinkService.java
> +        var link = jdbcLinkRepository.findLinkByUrl(stringUrl);
Добавил Optional

2024-03-24 14:49 UTC, Listoc commented on scrapper/src/main/java/edu/java/scrapper/controller/LinksController.java
> +        linkService.remove(id, linkRequest.url());
Теперь ошибка не выбрасывается, если ссылку не нашли. Но добавил выбрасывание ошибки, если чат не зарегистрирован (не только для удаления).

2024-03-24 14:50 UTC, Listoc commented on scrapper/src/main/java/edu/java/scrapper/controller/TelegramChatIdController.java
> +        jdbcTgChatService.unregister(id);
Также изменил

2024-03-24 14:55 UTC, Listoc commented on scrapper/src/main/java/edu/java/scrapper/service/jdbc/JdbcLinkUpdater.java
> +public class JdbcLinkUpdater implements LinkUpdater {
Изменил под такую логику, спасибо

Пока только не очень уверен в возвращаемых значениях у LinkUpdateProcessorService. Если ссылка не для этого ресурса, то возвращаю null, если изменений нет, то пустую ссылку.

2024-03-27 12:23 UTC, YuriiKondratov commented on scrapper/src/main/java/edu/java/scrapper/service/jdbc/JdbcLinkUpdater.java
> +public class JdbcLinkUpdater implements LinkUpdater {
Я бы вообще не стал разделять обработку этих случаев. Если есть что ответить - возвращаем сообщение, если нечего ответить (из-за того что ссылка не подходит или из-за того что изменений нет - не важно) - возвращаем null. Если хочется разграничить, то можно обернуть сообщение в дтошку типа:
```java
public class LinkUpdaterResult {
    String message;
    UpdateResult result;
}

enum UpdateResult {
    UPDATED,
    NO_UPDATES,
    NOT_SUPPORTED_LINK
}
```

2024-03-27 12:23 UTC, YuriiKondratov approved these changes

2024-03-27 12:59 UTC, merged